pipeline {
    agent any

    environment {
        APP_NAME = "jde-backend"
        IMAGE_NAME = "jde-backend:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    cd back/main-server
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker stop ${APP_NAME} || true
                    docker rm ${APP_NAME} || true
		    
		    # 독커 네트워크 묵기
		    docker network inspect JDE-local-network >/dev/null 2>&1 || docker network create JDE-local-network
                    docker run -d --name ${APP_NAME} --network JDE-local-network -p 8080:8080 ${IMAGE_NAME}
                    
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
