pipeline {
    agent any

    environment {
        APP_NAME = "jde-frontend"
        IMAGE_NAME = "jde-frontend:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    cd frontend/JDE
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker stop ${APP_NAME} || true
                    docker rm ${APP_NAME} || true
                    docker run -d --name ${APP_NAME} -p 80:80 ${IMAGE_NAME}
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
