// src/entities/restaurant/dummy.ts
// 목적: 임시 데이터 제공 (API 확정 전까지 사용)
// 교체 포인트: 실제 API 연동 시 이 파일 제거 후 widgets에서 API 호출로 대체

import type { Restaurant } from './types'

export const DUMMY_RESTAURANTS: Restaurant[] = [
  {
    restaurant_id: 1,
    name: '봉추찜닭',
    address: '서울 강남구 테헤란로 123',
    phone: '02-000-0001',
    summary: '매콤달콤한 찜닭 전문점',
    image: ['/images/r1-1.jpg', '/images/r1-2.jpg'],
    category: '한식',
    rating: 4.6,
    price_range: '₩₩',
    website_url: 'https://example.com/r1',
    menu: [{ name: '찜닭', price: 28000 }, { name: '치즈찜닭', price: 32000 }],
    distance_m: 340,
    is_open: true,
  },
  {
    restaurant_id: 2,
    name: '을지로 골뱅이',
    address: '서울 중구 을지로 45',
    phone: '02-000-0002',
    summary: '추억의 골뱅이 무침과 소면',
    image: ['/images/r2-1.jpg'],
    category: '안주/포차',
    rating: 4.4,
    price_range: '₩₩',
    website_url: 'https://example.com/r2',
    menu: [{ name: '골뱅이무침', price: 22000 }, { name: '노가리', price: 6000 }],
    distance_m: 510,
    is_open: true,
  },
  {
    restaurant_id: 3,
    name: '마포돼지갈비',
    address: '서울 마포구 월드컵북로 11',
    phone: '02-000-0003',
    summary: '달달한 돼지갈비의 정석',
    image: ['/images/r3-1.jpg'],
    category: '고기',
    rating: 4.7,
    price_range: '₩₩₩',
    website_url: 'https://example.com/r3',
    menu: [{ name: '돼지갈비', price: 17000 }, { name: '냉면', price: 9000 }],
    distance_m: 790,
    is_open: false,
  },
  {
    restaurant_id: 4,
    name: '성수 닭꼬치',
    address: '서울 성동구 아차산로 22',
    phone: '02-000-0004',
    summary: '참숯에 구운 닭꼬치 바',
    image: ['/images/r4-1.jpg'],
    category: '이자카야',
    rating: 4.3,
    price_range: '₩₩',
    website_url: 'https://example.com/r4',
    menu: [{ name: '모듬꼬치', price: 18000 }, { name: '닭껍질꼬치', price: 5000 }],
    distance_m: 260,
    is_open: true,
  },
  {
    restaurant_id: 5,
    name: '역삼 돈카츠',
    address: '서울 강남구 역삼로 77',
    phone: '02-000-0005',
    summary: '두툼한 등심 돈카츠',
    image: ['/images/r5-1.jpg'],
    category: '일식',
    rating: 4.5,
    price_range: '₩₩',
    website_url: 'https://example.com/r5',
    menu: [{ name: '등심카츠', price: 12000 }, { name: '치즈카츠', price: 13000 }],
    distance_m: 620,
    is_open: true,
  },
  {
    restaurant_id: 6,
    name: '홍대 파스타집',
    address: '서울 마포구 와우산로 33',
    phone: '02-000-0006',
    summary: '크림·로제·오일 파스타',
    image: ['/images/r6-1.jpg'],
    category: '이탈리안',
    rating: 4.2,
    price_range: '₩₩',
    website_url: 'https://example.com/r6',
    menu: [{ name: '까르보나라', price: 15000 }, { name: '봉골레', price: 14000 }],
    distance_m: 980,
    is_open: true,
  },
  {
    restaurant_id: 7,
    name: '건대 김치찌개',
    address: '서울 광진구 능동로 19',
    phone: '02-000-0007',
    summary: '시원한 김치찌개와 계란말이',
    image: ['/images/r7-1.jpg'],
    category: '한식',
    rating: 4.1,
    price_range: '₩',
    website_url: 'https://example.com/r7',
    menu: [{ name: '김치찌개', price: 8000 }, { name: '계란말이', price: 7000 }],
    distance_m: 410,
    is_open: true,
  },
  {
    restaurant_id: 8,
    name: '이태원 타코',
    address: '서울 용산구 이태원로 123',
    phone: '02-000-0008',
    summary: '정통 멕시칸 타코 & 퀘사디야',
    image: ['/images/r8-1.jpg'],
    category: '멕시칸',
    rating: 4.5,
    price_range: '₩₩',
    website_url: 'https://example.com/r8',
    menu: [{ name: '타코(2P)', price: 11000 }, { name: '퀘사디야', price: 13000 }],
    distance_m: 1240,
    is_open: false,
  },
  {
    restaurant_id: 9,
    name: '서촌 국수',
    address: '서울 종로구 자하문로 12',
    phone: '02-000-0009',
    summary: '깔끔한 멸치국수와 비빔국수',
    image: ['/images/r9-1.jpg'],
    category: '분식/면',
    rating: 4.0,
    price_range: '₩',
    website_url: 'https://example.com/r9',
    menu: [{ name: '멸치국수', price: 6000 }, { name: '비빔국수', price: 7000 }],
    distance_m: 300,
    is_open: true,
  },
  {
    restaurant_id: 10,
    name: '강남 초밥',
    address: '서울 강남구 강남대로 390',
    phone: '02-000-0010',
    summary: '가성비 초밥 세트',
    image: ['/images/r10-1.jpg'],
    category: '일식',
    rating: 4.8,
    price_range: '₩₩₩',
    website_url: 'https://example.com/r10',
    menu: [{ name: '모둠초밥(10P)', price: 22000 }, { name: '연어초밥', price: 21000 }],
    distance_m: 1430,
    is_open: true,
  },
]
